apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  params:
    - name: who
      type: string
      default: "IRAJ"
  steps:
    - name: build-sources
      image: ubuntu
      command:
      - /bin/bash
      - -c
      - echo "Hello World"
      - echo "Hello Iraj"
      # command:
      #   - /bin/bash
      # args: ['-c', 'echo hello Iraj']
    - name: build-sources2
      image: ubuntu
      command:
      - /bin/bash
      - -c
      - echo "Hello Iraj"
      # command:
      #   - /bin/bash
      # args: ['-c', 'echo hello Iraj']

    # - name: step-with-script
    #   image: ubuntu
    #   script: |
    #     #!/usr/bin/env bash
    #     echo "Installing necessary tooling"
    #     apt update
    #     apt-get install iputils -y
    #     ping google.com -c 5
    #     echo "All done!"

    - name: build-sources3
      image: ubuntu
      command:
      - /bin/bash
      - -c
      - echo "Hello $(params.who)"
